name: Release

on:
  push:
    tags:
      - '*'

jobs:
  linux-x86_64-static:
    name: Release binary for Linux x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: cmake --version
    - uses: gmiam/rust-musl-action@master
    - name: Build binaries
      run: cargo build --target x86_64-unknown-linux-musl --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-unknown-linux-musl/release/ic-cdk-optimizer
        asset_name: ic-cdk-optimizer-linux-x86_64
        tag: ${{ github.ref }}

  macos-x86_64:
    name: Release binary for MacOS x86_64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/ic-cdk-optimizer
        asset_name: ic-cdk-optimizer-macos-x86_64
        tag: ${{ github.ref }}
